name: Rust

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install nasm
      env:
        NASM_PKG: nasm-2.14.02
      run: |
        wget https://www.nasm.us/pub/nasm/releasebuilds/2.14.02/$NASM_PKG.tar.gz
        tar -xvf $NASM_PKG.tar.gz
        cd $NASM_PKG
        ./autogen.sh
        ./configure --prefix=$HOME/nasm_dir
        make
        make install
    - name: Run tests
      run: |
        export PATH=$HOME/nasm_dir/bin:$PATH
        cargo test --verbose
